### ISSUE TITLE
Huge amount of files for frontend folder (web-ui)

### ISSUE THREAD

**Issue by lutzilutz** [unige-pinfo-2019/PInfo2#4]
As you may have noticed, the first commit for the frontend pushed more than 3 million lines of code. Did I do something wrong ? The current frontend only contains the navigation bar (menu). It's not actually an issue, but we should stay aware of it, and maybe change something if needed.

Any advice or idea are welcome !

NB : I assigned Heloy and myself by default.

**Comment by jeremie-martin** [comment]
Compiling the frontend, with whatever framework you're using, will likely generate tons of files. Plus if you commit all the modules as well, you get your 25,823 files changed and 3,361,817 additions.

In order to prevent this kind of commit (you don't want to include the build or module folders), you should use the .gitignore file.

**Comment by lutzilutz** [comment]
Thanks for the quick reply ! We'll look into it and close the issue as soon as it is resolved.

**Comment by CorentinBT** [comment]
Fixed.
